#ifndef MATRIXMANIPULATION_CLI_MENU_FUNCTION_ACCUMULATENEGATIVELOWERVALUES_H
#define MATRIXMANIPULATION_CLI_MENU_FUNCTION_ACCUMULATENEGATIVELOWERVALUES_H


#include "Menu/Menu.h"

namespace MatrixManipulation {
	namespace CLI {
		void AccumulateNegativeLowerValues(Menu*);
	}
}


#endif //MATRIXMANIPULATION_CLI_MENU_FUNCTION_ACCUMULATENEGATIVELOWERVALUES_H