#ifndef MATRIXMANIPULATION_CLI_MENU_FUNCTION_CREATEMATRIX_H
#define MATRIXMANIPULATION_CLI_MENU_FUNCTION_CREATEMATRIX_H


#include "Menu/Menu.h"

namespace MatrixManipulation {
	namespace CLI {
		void CreateMatrix(Menu*);
	}
}


#endif //MATRIXMANIPULATION_CLI_MENU_FUNCTION_CREATEMATRIX_H