#ifndef MATRIXMANIPULATION_CLI_MENU_FUNCTION_REPLACEZEROROWS_H
#define MATRIXMANIPULATION_CLI_MENU_FUNCTION_REPLACEZEROROWS_H


#include "Menu/Menu.h"

namespace MatrixManipulation {
	namespace CLI {
		void ReplaceZeroRows(Menu*);
	}
}


#endif //MATRIXMANIPULATION_CLI_MENU_FUNCTION_REPLACEZEROROWS_H