#ifndef MATRIXMANIPULATION_CLI_MENU_FUNCTION_SORTROWSBYSIGNATURE_H
#define MATRIXMANIPULATION_CLI_MENU_FUNCTION_SORTROWSBYSIGNATURE_H


#include "Menu/Menu.h"

namespace MatrixManipulation {
	namespace CLI {
		void SortRowsBySignature(Menu*);
	}
}


#endif //MATRIXMANIPULATION_CLI_MENU_FUNCTION_SORTROWSBYSIGNATURE_H